/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        destructive: 'var(--destructive)',
        'destructive-foreground': 'var(--destructive-foreground)',
        border: 'var(--border)',
        input: 'var(--input)',
        'input-background': 'var(--input-background)',
        'switch-background': 'var(--switch-background)',
        ring: 'var(--ring)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        sidebar: 'var(--sidebar)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        'sidebar-primary': 'var(--sidebar-primary)',
        'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
        'sidebar-accent': 'var(--sidebar-accent)',
        'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
        'sidebar-border': 'var(--sidebar-border)',
        'sidebar-ring': 'var(--sidebar-ring)',
        'torch-red': {
          50: '#fff0f2',
          100: '#ffdee2',
          200: '#ffc2ca',
          300: '#ff98a6',
          400: '#ff5d73',
          500: '#ff2b47',
          600: '#f71735',
          700: '#d00520',
          800: '#ab091f',
          900: '#8d0f20',
          950: '#4e010b',
        },
        'bright-turquoise': {
          50: '#f0fdfa',
          100: '#cbfcf3',
          200: '#97f8e8',
          300: '#41ead4',
          400: '#2ad7c7',
          500: '#11bbae',
          600: '#0a978e',
          700: '#0d7873',
          800: '#0f605c',
          900: '#124f4d',
          950: '#033030',
        },
        'black-pearl': {
          50: '#eff8ff',
          100: '#ddf1ff',
          200: '#b4e4ff',
          300: '#71d0ff',
          400: '#26baff',
          500: '#00a1fd',
          600: '#0080d9',
          700: '#0065b0',
          800: '#005591',
          900: '#034777',
          950: '#011627',
        },
      },
    },
  },
  plugins: [],
};
