import { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ka';

const TRANSLATIONS = {
  en: {
    header: {
      home: 'Home',
      features: 'Features',
      pricing: 'Pricing',
      about: 'About',
      teach: 'Teach',
      dashboard: 'Dashboard',
      login: 'Login',
      signup: 'Sign Up',
      toggleTheme: 'Toggle theme',
      toggleMenu: 'Toggle menu',
    },
    footer: {
      company: 'Company',
      resources: 'Resources',
      legal: 'Legal',
      stayUpdated: 'Stay Updated',
      newsletter: 'Subscribe to our newsletter for learning tips and updates.',
      aboutUs: 'About Us',
      careers: 'Careers',
      press: 'Press',
      blog: 'Blog',
      helpCenter: 'Help Center',
      teachers: 'Teachers',
      community: 'Community',
      contactUs: 'Contact Us',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookiePolicy: 'Cookie Policy',
      licensing: 'Licensing',
      copyright: 'All rights reserved.',
      emailPlaceholder: 'Enter your email',
      subscribe: 'Subscribe',
    },
    sidebar: {
      dashboard: 'Dashboard',
      courses: 'Courses',
      history: 'History',
      feedback: 'Feedback',
      calendar: 'Calendar',
      assignments: 'Assignments',
      notifications: 'Notifications',
      settings: 'Settings',
      student: 'Student',
      teacher: 'Teacher',
      portal: 'Student Portal',
      logout: 'Log out',
    },
    auth: {
      backToHome: 'Back to home',
      loading: 'Loading...',
      firstName: 'First Name',
      lastName: 'Last Name',
      firstNamePlaceholder: 'John',
      lastNamePlaceholder: 'Doe',
      loginWelcome: 'Welcome back',
      loginSubtitle: 'Sign in to continue your learning journey',
      registerTitle: 'Create an account',
      registerSubtitle:
        'Start your learning journey today with curated lessons and expert teachers.',
      loginEmailDivider: 'Or continue with email',
      registerEmailDivider: 'Or register with email',
      signIn: 'Sign in',
      signUp: 'Sign up',
      continueWithGoogle: 'Continue with Google',
      facebook: 'Facebook',
      twitter: 'Twitter',
      emailAddress: 'Email Address',
      password: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      signInButton: 'Sign in',
      signingIn: 'Signing in...',
      createAccount: 'Create account',
      creatingAccount: 'Creating account...',
      loginFailed: 'Login failed',
      registrationFailed: 'Registration failed',
      accountCreated: 'Account created! You can now login.',
      alreadyHaveAccount: 'Already have an account?',
      doNotHaveAccount: "Don't have an account?",
    },
    landing: {
      heroBadge: 'Now accepting new students',
      heroTitlePre: 'Master English with',
      heroTitleEmphasis: 'Expert Teachers',
      heroSubtitle:
        'Join thousands of students learning English through personalized 1-on-1 lessons and interactive group classes. Start your journey today.',
      heroPrimaryCta: 'Get Started Free',
      heroSecondaryCta: 'View Classes',
      heroStatsStudents: 'Active Students',
      heroStatsTeachers: 'Expert Teachers',
      heroStatsRating: 'Average Rating',
      heroNextLesson: 'Next lesson starts in',
      heroNextLessonCountdown: '15 minutes',
      featuresTitlePre: 'Everything you need to',
      featuresTitleEmphasis: 'master English',
      featuresSubtitle:
        'Our platform combines cutting-edge technology with proven teaching methods to deliver an unmatched learning experience.',
      featuresBadge: 'Features',
      featuresCta: 'Ready to start your learning journey?',
      featuresViewPricing: 'View Pricing Plans',
      featureEasySchedulingTitle: 'Easy Scheduling',
      featureEasySchedulingDescription:
        'Book 1-on-1 lessons or group classes with just a few clicks. Our smart calendar system makes scheduling effortless.',
      featureGroupClassesTitle: 'Group Classes',
      featureGroupClassesDescription:
        'Join small group classes (4 students max) for collaborative learning experiences and peer interaction.',
      featureCefrTitle: 'CEFR-Aligned Courses',
      featureCefrDescription:
        'Structured courses from A1 to C2 levels, perfectly aligned with international language standards.',
      featureProgressTitle: 'Progress Tracking',
      featureProgressDescription:
        'Monitor your improvement with detailed feedback, lesson history, and skill assessments.',
      featureVideoTitle: 'Live Video Lessons',
      featureVideoDescription:
        'High-quality video conferencing built-in. Learn face-to-face with teachers from anywhere.',
      featureFlexibleTitle: 'Flexible Schedule',
      featureFlexibleDescription:
        'Learn at your own pace with 24/7 availability. Choose times that work best for your lifestyle.',
      aboutBadge: 'About Us',
      aboutTitlePre: 'Your trusted partner in',
      aboutTitleEmphasis: 'language learning',
      aboutParagraph1:
        'British World has been revolutionizing online language education since 2014. We\'ve helped thousands of students achieve their English language goals through personalized instruction and innovative technology.',
      aboutParagraph2:
        'Our platform combines the expertise of certified teachers with cutting-edge learning tools to create an engaging, effective, and flexible learning experience. Whether you\'re preparing for exams, advancing your career, or simply love learning, we\'re here to support your journey.',
      aboutParagraph3:
        'With a community of over 10,000 active students and 500+ qualified teachers, British World is more than just a learning platform-it\'s a global community dedicated to language excellence.',
      aboutYearsExperience: 'Years Experience',
      valueExcellenceTitle: 'Excellence',
      valueExcellenceDescription:
        'We maintain the highest standards in teaching and student support.',
      valueCommunityTitle: 'Global Community',
      valueCommunityDescription:
        'Connect with students and teachers from around the world.',
      valueStudentCenteredTitle: 'Student-Centered',
      valueStudentCenteredDescription:
        'Your learning goals and success are at the heart of everything we do.',
      valueTrustTitle: 'Trust & Safety',
      valueTrustDescription:
        'Verified teachers, secure payments, and a safe learning environment.',
      pricingBadge: 'Pricing',
      pricingTitlePre: 'Simple, transparent',
      pricingTitleEmphasis: 'pricing',
      pricingSubtitle:
        'Choose the plan that fits your learning goals. All plans include access to certified teachers and our full platform features.',
      pricingFooterNote: 'Prices shown in EUR for group classes.',
      pricingFooterCustom: 'Need a custom plan?',
      contactUs: 'Contact us',
      viewPricingPlans: 'View Pricing Plans',
    },
    pricing: {
      tokensLabel: 'Tokens',
      perLesson: 'per lesson',
      save: 'Save',
      mostPopular: 'Most Popular',
      getStarted: 'Get Started',
      needCustomPlan: 'Need a custom plan?',
      contactUs: 'Contact us',
      alignedNote: 'Lingoda-aligned prices shown in EUR for group classes.',
      features: {
        fourLessons: '4 live group lessons',
        eightLessons: '8 live group lessons',
        sixteenLessons: '16 live group lessons',
        thirtyTwoLessons: '32 live group lessons',
        flexibleScheduling: 'Flexible scheduling',
        progressTracking: 'Progress tracking',
        balancedWeeklyPace: 'Balanced weekly pace',
        lessonReminders: 'Lesson reminders',
        discountedTier: '20% discounted tier',
        detailedProgressReports: 'Detailed progress reports',
        mostPopularTier: 'Most popular Lingoda tier',
        comprehensiveFeedback: 'Comprehensive feedback',
        prioritySupport: 'Priority support',
        intensiveSchedule: 'Intensive learning schedule',
      },
    },
    dashboard: {
      welcomeStudent: 'Welcome back',
      welcomeTeacher: 'Welcome back',
      availableTokens: 'Available Tokens',
      hoursCompleted: 'Hours Completed',
      completedLessons: 'Completed',
      availableLessons: 'Available Lessons',
      avgRatingLabel: 'Avg Rating',
      topUp: 'Top up',
      topUpShort: 'Top up',
      performanceOverview: 'Performance Overview',
      completionRate: 'Completion Rate',
      activeStudents: 'Active Students',
      ratingBasedOn: 'Based on {count} student ratings',
      ratingUnavailable: 'Available after students rate your lessons',
      teacherSummary:
        'You have {upcoming} upcoming lessons and {completed} completed.',
      tokenDetailsOneOnOne: '1-on-1',
      tokenDetailsGroup: 'Group',
      tokenDetailsFlexible: 'Flexible',
      lessonsLabel: 'lessons',
      totalStudents: 'Total Students',
      pendingAnyAvailableTeacher: 'Any Available Teacher',
      waitingForTeacherConfirmation: 'Waiting for teacher confirmation...',
      waitingForAnyTeacher: "Waiting for any teacher to accept...",
      teacherTip: "💡 Tip: Teachers usually respond within 24 hours. You'll receive a notification once they accept!",
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      viewAll: 'View All',
      todaySchedule: "Today's Schedule",
      recentActivity: 'Recent Activity',
      scheduleNewLesson: '+ Schedule New Lesson',
      upcomingLessons: 'Upcoming Lessons',
      pendingRequests: 'Pending Requests',
      openGroupClasses: 'Open Group Classes',
      available: 'available',
      coursesComingSoon: 'Courses Coming Soon!',
      assignmentsComingSoon: 'Assignments Coming Soon!',
      noUpcomingLessons: 'No upcoming lessons',
      noRecentActivity: 'No recent activity',
      noLessonsFound: 'No lessons found',
      lessonsFound: 'lesson(s) found',
      historyWillAppearHere: 'Your lesson history will appear here',
      lessonHistory: 'Lesson History',
      feedback: 'Feedback',
      feedbackTeacherSubtitle:
        'Close finished lessons and review attendance in one place.',
      feedbackStudentSubtitle:
        'Read teacher comments and confirm attendance for completed lessons.',
      feedbackNeedsAttention: 'Needs your attention',
      feedbackReady: 'Ready to review',
      feedbackCompleted: 'Completed',
      feedbackActionNeeded: 'Action needed',
      feedbackReview: 'Review',
      openFeedback: 'Open',
      noFeedbackPending: 'Nothing pending right now',
      feedbackEmptyHint:
        'Lessons appear here after they end and need attendance or feedback.',
      noCompletedFeedback: 'No closed lessons yet.',
      level: 'Level',
      joinGroup: 'Join Group',
      joining: 'Joining...',
      noOpenGroupClasses: 'No open group classes right now. Check back soon.',
    },
    levels: {
      'A1.1': 'A1.1',
      'A1.2': 'A1.2',
      'A2.1': 'A2.1',
      'A2.2': 'A2.2',
      'B1.1': 'B1.1',
      'B1.2': 'B1.2',
      'B2.1': 'B2.1',
      'B2.2': 'B2.2',
      'C1.1': 'C1.1',
      'C1.2': 'C1.2',
      'C2.1': 'C2.1',
      'C2.2': 'C2.2',
    },
    calendar: {
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      scheduleNewLesson: 'Schedule New Lesson',
      rescheduleLesson: 'Reschedule Lesson',
      lessonTopic: 'Lesson Topic',
      level: 'Level',
      lessonFocus: 'Lesson Focus (Optional)',
      lessonFocusPlaceholder: 'What would you like to focus on in this lesson?',
      selectDate: 'Select Date',
      selectTime: 'Select Time',
      hour: 'Hour',
      minute: 'Minute',
      lessonType: 'Lesson Type',
      groupClass: 'Group Class',
      oneOnOneLesson: '1-on-1 Lesson',
      personalCoaching: 'Personal coaching',
      upToStudents: 'Up to 5 students',
      groupClassesInfo: 'Group classes proceed when at least 2 students are joined.',
      scheduleLesson: 'Schedule Lesson',
      reschedule: 'Reschedule Lesson',
      cancel: 'Cancel',
      classFormat: 'Class Format',
      lessonStatus: 'Lesson Status',
      date: 'Date',
      teacher: 'Teacher',
      student: 'Student',
      untitledLesson: 'Untitled Lesson',
      openTeacherAccept: 'Open - tap to accept',
      openGroupAccept: 'tap to accept',
      joined: 'joined',
      time: 'Time',
      duration: 'Duration',
      view: 'View',
      notAssigned: 'Not Assigned',
      bookLesson: 'Book Lesson',
      calendarTitle: 'Calendar',
      teacherOpenSummary: 'Open requests from students and lessons you have accepted',
      studentSummary: 'Schedule your English lessons',
      joinedStudents: 'Joined Students',
      close: 'Close',
      joinLesson: 'Join lesson',
      cancelLesson: 'Cancel lesson',
      accepting: 'Accepting...',
      acceptGroup: 'Accept group',
      acceptLesson: 'Accept lesson',
      unknownStudent: 'Unknown student',
      openAnyTeacher: 'Open — any teacher can accept',
      scheduledLesson: 'Scheduled Lesson',
      inProgress: 'In Progress',
      finished: 'Finished',
      missedByStudent: 'Missed by Student',
      missedByTeacher: 'Missed by Teacher',
      cancelledByStudent: 'Cancelled by Student',
      cancelledByTeacher: 'Cancelled by Teacher',
      cancelledBySystem: 'Cancelled by System',
      lessonAcceptedTitle: 'Lesson accepted',
      lessonAcceptedMessage: 'You have accepted this lesson request.',
      acceptFailedTitle: 'Accept failed',
      acceptFailedMessage: 'Could not accept this lesson.',
      alreadyJoinedTitle: 'Already Joined',
      joinedGroupTitle: 'Joined Group Class',
      alreadyJoinedMessage: 'You are already in this group class.',
      joinedSuccessMessage: 'Joined successfully',
      studentsCountSuffix: 'students',
      joinFailedTitle: 'Join Failed',
      joinFailedMessage: 'Could not join this lesson.',
      classFullMessage: 'This class is full, unavailable, or no longer open for joining.',
      joining: 'Joining...',
      joinGroupClass: 'Join Group Class',
      timePrefix: 'at',
      tokenCost: 'Token Cost',
      availableTokensForThisLessonTypePrefix: 'Available for this lesson type:',
      availableTokensForThisLessonTypeSuffix: '(including flexible tokens)',
      noTokenAvailablePrefix: 'No',
      noTokenAvailableSuffix: 'available. Please top up to schedule.',
      tokenLabelOneOnOne: '1-on-1 token',
      tokenLabelGroup: 'group token',
      mustBeAtLeast24Hours: 'Must be at least 24 hours in the future.',
      conflictsWithExistingLesson: 'Conflicts with an existing lesson.',
      newTimeMustBeDifferent: 'New time must be different from current time.',
      cannotScheduleLesson: 'Cannot schedule lesson',
      lessonScheduled: 'Lesson Scheduled',
      lessonScheduledMessage: 'Your lesson has been successfully scheduled.',
      failedToScheduleLesson: 'Failed to schedule lesson',
      notEnoughTokensPrefix: 'You do not have enough',
      notEnoughTokensSuffix: 's.',
      schedulingFailed: 'Scheduling Failed',
      cannotRescheduleLesson: 'Cannot reschedule lesson',
      lessonRescheduled: 'Lesson Rescheduled',
      lessonRescheduledMessage: 'Your lesson has been successfully rescheduled.',
      failedToRescheduleLesson: 'Failed to reschedule lesson',
      reschedulePermissionDenied: 'You are not allowed to reschedule other people\'s lessons',
      reschedulingFailed: 'Rescheduling Failed',
    },
    notifications: {
      title: 'Notifications',
      youHave: 'You have',
      notificationSingular: 'notification',
      notificationPlural: 'notifications',
      all: 'All',
      unread: 'Unread',
      read: 'Read',
      newest: 'Newest',
      oldest: 'Oldest',
      noNotifications: 'No notifications',
      caughtUp: "You're all caught up!",
      noRead: 'No read notifications yet',
      checkBack: 'Check back later for updates',
      newBadge: 'New',
      from: 'From',
      messageLabel: 'Message',
      close: 'Close',
      markAsRead: 'Mark as Read',
    },
    setup: {
      title: 'Finish setting up your account',
      subtitle: 'Please add your first and last name. This is a one-time update.',
      firstName: 'First name',
      lastName: 'Last name',
      firstNamePlaceholder: 'Enter your first name',
      lastNamePlaceholder: 'Enter your last name',
      nameTooShort: 'First and last name must be at least 2 characters.',
      updateFailed: 'Failed to update your name.',
      save: 'Save name',
      saving: 'Saving...',
    },
    cancelLesson: {
      confirmTitle: 'Cancel this lesson?',
      refundWarning:
        'You can cancel this lesson, but your lesson token will not be refunded because it is within 24 hours of the scheduled time.',
      refundOk:
        'You can cancel this lesson and your lesson token will be refunded.',
      keepLesson: 'Keep Lesson',
      confirmButton: 'Cancel Lesson',
      cancelling: 'Cancelling...',
      successTitle: 'Class Cancelled',
      successMessage: 'The class has been successfully cancelled.',
      missingIds: 'Missing class id or user id, cannot cancel',
      failed: 'Failed to cancel class',
      errorGeneric: 'Error cancelling class',
    },
    topUpModal: {
      balanceSuffix: 'tokens',
      demoNotice:
        'Demo mode — no real payment is processed. Tokens are added instantly for testing.',
      tokenType: 'Token Type',
      groupTokens: 'Group Tokens',
      oneOnOneTokens: '1-on-1 Tokens',
      customAmount: 'Buy Custom Amount (1-3 tokens)',
      tokenSingular: 'Token',
      tokenPlural: 'Tokens',
      saveWithBundles: 'Save with Bundles',
      mostPopular: 'MOST POPULAR',
      perToken: 'per token',
      save: 'Save',
      paymentMethod: 'Payment Method',
      methodCard: 'Credit / Debit Card',
      methodApplePay: 'Apple Pay',
      methodPaypal: 'PayPal',
      cardDetails: 'Card Details',
      cardNumber: 'Card Number',
      expiryDate: 'Expiry Date',
      cvv: 'CVV',
      selectedBundle: 'Selected Bundle:',
      discount: 'Discount:',
      total: 'Total:',
      cancel: 'Cancel',
      processing: 'Processing...',
      pay: 'Pay',
      securityNote: '🔒 Your payment information is secure and encrypted',
      successTitle: 'Purchase Successful',
      successMessage: 'Added {count} {type}.',
      failedTitle: 'Purchase Failed',
      failedGeneric: 'Could not complete token purchase.',
      failedAuth: 'Please log in again and retry.',
      failedBundle: 'Invalid token bundle selected. Please retry.',
    },
    lessonFeedback: {
      yesAttended: 'Yes, attended',
      noMissed: 'No, missed',
      attendanceRequired: 'Attendance required',
      confirmTeacherAttendedPrompt:
        'Please confirm whether your teacher attended.',
      attendanceRecorded: 'Attendance recorded',
      thanksForRating: 'Thank you for rating your teacher.',
      reportSubmitted: 'Your report was submitted.',
      couldNotSubmit: 'Could not submit',
      tryAgain: 'Please try again.',
      absentNoRating:
        'You were marked absent for this lesson, so teacher rating is not available.',
      confirmTeacherAttendance: 'Confirm teacher attendance',
      teacherReportedMissing:
        'Your teacher reported missing this lesson. Please confirm what happened.',
      didTeacherAttendQuestion: 'Did your teacher attend this lesson?',
      youReported: 'You reported:',
      teacherAttended: 'Teacher attended',
      teacherMissed: 'Teacher missed the lesson',
      didTeacherAttendLabel: 'Did your teacher attend?',
      commentOptional: 'Comment (optional)',
      commentPlaceholderPositive: 'What did you enjoy? What could be improved?',
      commentPlaceholderNegative: 'Add any details about what happened...',
      submitting: 'Submitting...',
      submitAttendance: 'Submit attendance',
      loadingLesson: 'Loading lesson details...',
      waitingForTeacherToClose: 'Waiting for the teacher to close this lesson.',
      teacherMissedLesson: 'Your teacher reported missing this lesson.',
      markedAbsent: 'You were marked absent for this lesson.',
      teacherFeedback: 'Teacher feedback',
      newBadge: 'New',
      openMaterials: 'Open shared materials',
      lessonClosed: 'Lesson closed',
      youReportedMissing: 'You reported missing this lesson.',
      attendanceSubmitted:
        'Attendance and feedback for this lesson have been submitted.',
      studentsAttended: '{attended}/{total} students attended',
      opensAfterLesson: 'Feedback opens after the lesson ends.',
      completeLesson: 'Complete lesson',
      completeLessonHint:
        'Confirm your attendance, then record each student\'s attendance and feedback.',
      didYouAttend: 'Did you attend this lesson?',
      iMissedLesson: 'I missed this lesson',
      confirmYouAttendedPrompt:
        'Please confirm whether you attended this lesson.',
      markedMissedTitle: 'Lesson marked as missed',
      markedMissedMessage: 'Students will be notified to confirm attendance.',
      feedbackRequiredTitle: 'Feedback required',
      feedbackRequiredMessage: 'Students who attended need a feedback comment.',
      lessonCompletedTitle: 'Lesson completed',
      lessonCompletedMessage: 'Attendance and feedback were saved.',
      studentFallback: 'Student',
      didStudentAttend: 'Did this student attend?',
      rating: 'Rating',
      starSingular: 'star',
      starPlural: 'stars',
      feedbackComment: 'Feedback comment *',
      feedbackCommentPlaceholder:
        'What went well? What should the student practice next?',
      materialsLink: 'Materials link (optional)',
      noteOptional: 'Note (optional)',
      notePlaceholder: 'Optional note about the absence...',
      submitAttendanceFeedback: 'Submit attendance & feedback',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Manage your account preferences and settings',
      emailPushTitle: 'Email & Push Notifications',
      emailPushBody:
        'Always enabled so you never miss updates about your lessons, assignments, and platform announcements.',
      theme: 'Theme',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      userMode: 'User Mode',
      accessText:
        'You have access to both Student and Teacher modes. Switch between them to access different features.',
      currentModeTeacher: 'Teacher Mode',
      currentModeStudent: 'Student Mode',
      notificationPreferences: 'Notification Preferences',
      adsEmails: 'Advertisement & Sales Emails',
      becomeTeacher: 'Become a Teacher',
      becomeTeacherBody:
        'Ready to share your teaching experience? Apply to become a teacher on our platform and start earning money by teaching students worldwide.',
      applicationPending: 'Your application is currently under review.',
      applicationApproved: 'You are already approved as a teacher.',
      applicationRejected:
        'Your application was not approved. Contact support to reapply.',
      applyButton: 'Apply to be a Teacher',
      profileSettings: 'Profile Settings',
      fullName: 'Full Name',
      email: 'Email',
      phone: 'Phone',
      language: 'Language',
      english: 'English',
      georgian: 'Georgian',
    },
  },
  ka: {
    header: {
      home: 'მთავარი',
      features: 'ფუნქციები',
      pricing: 'ფასები',
      about: 'ჩვენ შესახებ',
      teach: 'ასწავლე',
      dashboard: 'დეშბორდი',
      login: 'შესვლა',
      signup: 'რეგისტრაცია',
      toggleTheme: 'თემის გადართვა',
      toggleMenu: 'მენიუს გადართვა',
    },
    footer: {
      company: 'კომპანია',
      resources: 'რესურსები',
      legal: 'სამართლებრივი',
      stayUpdated: 'იყავი კურსში',
      newsletter: 'გამოიწერე სიახლეები და მიიღე სასწავლო რჩევები და განახლებები.',
      aboutUs: 'ჩვენ შესახებ',
      careers: 'ვაკანსიები',
      press: 'პრესა',
      blog: 'ბლოგი',
      helpCenter: 'დახმარების ცენტრი',
      teachers: 'მასწავლებლები',
      community: 'საზოგადოება',
      contactUs: 'დაგვიკავშირდი',
      privacyPolicy: 'კონფიდენციალურობის პოლიტიკა',
      termsOfService: 'მომსახურების პირობები',
      cookiePolicy: 'ქუქი-ფაილების პოლიტიკა',
      licensing: 'ლიცენზირება',
      copyright: 'ყველა უფლება დაცულია.',
      emailPlaceholder: 'შეიყვანე ელფოსტა',
      subscribe: 'გამოწერა',
    },
    sidebar: {
      dashboard: 'დეშბორდი',
      courses: 'კურსები',
      history: 'ისტორია',
      feedback: 'უკუკავშირი',
      calendar: 'კალენდარი',
      assignments: 'დავალებები',
      notifications: 'შეტყობინებები',
      settings: 'პარამეტრები',
      student: 'სტუდენტი',
      teacher: 'მასწავლებელი',
      portal: 'სტუდენტის პორტალი',
      logout: 'გასვლა',
    },
    auth: {
      backToHome: 'მთავარზე დაბრუნება',
      loading: 'იტვირთება...',
      firstName: 'სახელი',
      lastName: 'გვარი',
      firstNamePlaceholder: 'გიორგი',
      lastNamePlaceholder: 'ბერიძე',
      loginWelcome: 'კვლავ მოგესალმებით',
      loginSubtitle: 'შედი ანგარიშში და გააგრძელე სწავლა',
      registerTitle: 'ანგარიშის შექმნა',
      registerSubtitle:
        'დაიწყე სწავლა დღესვე — შერჩეული გაკვეთილები და გამოცდილი მასწავლებლები გელოდება.',
      loginEmailDivider: 'ან გააგრძელე ელფოსტით',
      registerEmailDivider: 'ან დარეგისტრირდი ელფოსტით',
      signIn: 'შესვლა',
      signUp: 'რეგისტრაცია',
      continueWithGoogle: 'გაგრძელება Google-ით',
      facebook: 'Facebook',
      twitter: 'Twitter',
      emailAddress: 'ელფოსტის მისამართი',
      password: 'პაროლი',
      rememberMe: 'დამახსოვრება',
      forgotPassword: 'დაგავიწყდა პაროლი?',
      signInButton: 'შესვლა',
      signingIn: 'მიმდინარეობს შესვლა...',
      createAccount: 'ანგარიშის შექმნა',
      creatingAccount: 'მიმდინარეობს ანგარიშის შექმნა...',
      loginFailed: 'შესვლა ვერ მოხერხდა',
      registrationFailed: 'რეგისტრაცია ვერ მოხერხდა',
      accountCreated: 'ანგარიში წარმატებით შეიქმნა! ახლა უკვე შეგიძლია შეხვიდე.',
      alreadyHaveAccount: 'უკვე გაქვს ანგარიში?',
      doNotHaveAccount: 'არ გაქვს ანგარიში?',
    },
    landing: {
      heroBadge: 'ახალი სტუდენტების მიღება ღიაა',
      heroTitlePre: 'ინგლისურის დაუფლება',
      heroTitleEmphasis: 'პროფესიონალ მასწავლებლებთან',
      heroSubtitle:
        'ათასობით სტუდენტი უკვე სწავლობს ინგლისურს ინდივიდუალური გაკვეთილებითა და ინტერაქტიული ჯგუფური კლასებით. შემოგვიერთდი დღესვე.',
      heroPrimaryCta: 'დაწყება უფასოდ',
      heroSecondaryCta: 'კლასების ნახვა',
      heroStatsStudents: 'აქტიური სტუდენტი',
      heroStatsTeachers: 'პროფესიონალი მასწავლებელი',
      heroStatsRating: 'საშუალო შეფასება',
      heroNextLesson: 'შემდეგი გაკვეთილი დაიწყება',
      heroNextLessonCountdown: '15 წუთში',
      featuresTitlePre: 'ყველაფერი, რაც გჭირდება',
      featuresTitleEmphasis: 'ინგლისურის დასაუფლებლად',
      featuresSubtitle:
        'ჩვენი პლატფორმა აერთიანებს თანამედროვე ტექნოლოგიებსა და სწავლების დადასტურებულ მეთოდებს.',
      featuresBadge: 'ფუნქციები',
      featuresCta: 'მზად ხარ, დაიწყო სწავლა?',
      featuresViewPricing: 'ფასების ნახვა',
      featureEasySchedulingTitle: 'მარტივი დაგეგმვა',
      featureEasySchedulingDescription:
        'დაჯავშნე ინდივიდუალური გაკვეთილი ან ჯგუფური კლასი რამდენიმე დაწკაპუნებით. ჩვენი ჭკვიანი კალენდარი დაგეგმვას მაქსიმალურად ამარტივებს.',
      featureGroupClassesTitle: 'ჯგუფური კლასები',
      featureGroupClassesDescription:
        'შემოუერთდი მცირე ჯგუფებს (მაქსიმუმ 4 სტუდენტი) და ისწავლე სხვებთან ერთად, ცოცხალ დიალოგში.',
      featureCefrTitle: 'CEFR-ის სტანდარტზე მორგებული კურსები',
      featureCefrDescription:
        'სტრუქტურირებული კურსები A1-დან C2-მდე, სრულ შესაბამისობაში ენის საერთაშორისო სტანდარტებთან.',
      featureProgressTitle: 'პროგრესის თვალყურის დევნება',
      featureProgressDescription:
        'თვალი ადევნე შენს წინსვლას დეტალური უკუკავშირით, გაკვეთილების ისტორიითა და უნარების შეფასებით.',
      featureVideoTitle: 'ცოცხალი ვიდეოგაკვეთილები',
      featureVideoDescription:
        'ჩაშენებული, მაღალი ხარისხის ვიდეოკავშირი. ისწავლე მასწავლებელთან პირისპირ, ნებისმიერი ადგილიდან.',
      featureFlexibleTitle: 'მოქნილი განრიგი',
      featureFlexibleDescription:
        'ისწავლე შენივე ტემპით — გაკვეთილები ხელმისაწვდომია დღე-ღამის ნებისმიერ დროს. აირჩიე დრო, რომელიც შენს რიტმს მოერგება.',
      aboutBadge: 'ჩვენ შესახებ',
      aboutTitlePre: 'შენი სანდო პარტნიორი',
      aboutTitleEmphasis: 'ენის შესწავლაში',
      aboutParagraph1:
        'British World 2014 წლიდან ცვლის ენის ონლაინ სწავლებას. ჩვენ ათასობით სტუდენტს დავეხმარეთ ინგლისურის სწავლის მიზნების მიღწევაში — პერსონალური მიდგომითა და თანამედროვე ტექნოლოგიებით.',
      aboutParagraph2:
        'ჩვენი პლატფორმა აერთიანებს სერტიფიცირებული მასწავლებლების გამოცდილებასა და თანამედროვე სასწავლო ინსტრუმენტებს. იქნება ეს გამოცდისთვის მზადება, კარიერული წინსვლა თუ უბრალოდ სწავლის სიყვარული — ჩვენ შენს გვერდით ვდგავართ.',
      aboutParagraph3:
        '10 000-ზე მეტი აქტიური სტუდენტითა და 500-ზე მეტი კვალიფიციური მასწავლებლით, British World უბრალოდ სასწავლო პლატფორმაზე მეტია — ეს გლობალური საზოგადოებაა, რომელიც ენის სრულყოფილად ცოდნას ემსახურება.',
      aboutYearsExperience: 'წლის გამოცდილება',
      valueExcellenceTitle: 'სრულყოფილება',
      valueExcellenceDescription:
        'ჩვენ ვინარჩუნებთ სწავლებისა და სტუდენტების მხარდაჭერის უმაღლეს სტანდარტს.',
      valueCommunityTitle: 'გლობალური საზოგადოება',
      valueCommunityDescription:
        'დაუკავშირდი სტუდენტებსა და მასწავლებლებს მთელი მსოფლიოდან.',
      valueStudentCenteredTitle: 'სტუდენტზე მორგებული',
      valueStudentCenteredDescription:
        'ყველაფრის ცენტრში, რასაც ვაკეთებთ, შენი მიზნები და წარმატებაა.',
      valueTrustTitle: 'ნდობა და უსაფრთხოება',
      valueTrustDescription:
        'გადამოწმებული მასწავლებლები, უსაფრთხო გადახდები და დაცული სასწავლო გარემო.',
      pricingBadge: 'ფასები',
      pricingTitlePre: 'მარტივი და გამჭვირვალე',
      pricingTitleEmphasis: 'ფასები',
      pricingSubtitle:
        'აირჩიე პაკეტი, რომელიც შენს მიზნებს შეესაბამება. ყველა პაკეტი მოიცავს სერტიფიცირებულ მასწავლებლებთან წვდომას და პლატფორმის სრულ ფუნქციონალს.',
      pricingFooterNote: 'ფასები მოცემულია ევროში, ჯგუფური კლასებისთვის.',
      pricingFooterCustom: 'გჭირდება ინდივიდუალური პაკეტი?',
      contactUs: 'დაგვიკავშირდი',
      viewPricingPlans: 'ფასების ნახვა',
    },
    pricing: {
      tokensLabel: 'ტოკენი',
      perLesson: 'ერთ გაკვეთილზე',
      save: 'დაზოგე',
      mostPopular: 'ყველაზე პოპულარული',
      getStarted: 'დაწყება',
      needCustomPlan: 'გჭირდება ინდივიდუალური პაკეტი?',
      contactUs: 'დაგვიკავშირდი',
      alignedNote: 'ფასები მოცემულია ევროში და ეხება ჯგუფურ კლასებს.',
      features: {
        fourLessons: '4 ცოცხალი ჯგუფური გაკვეთილი',
        eightLessons: '8 ცოცხალი ჯგუფური გაკვეთილი',
        sixteenLessons: '16 ცოცხალი ჯგუფური გაკვეთილი',
        thirtyTwoLessons: '32 ცოცხალი ჯგუფური გაკვეთილი',
        flexibleScheduling: 'მოქნილი განრიგი',
        progressTracking: 'პროგრესის თვალყურის დევნება',
        balancedWeeklyPace: 'დაბალანსებული კვირეული ტემპი',
        lessonReminders: 'გაკვეთილის შეხსენებები',
        discountedTier: '20%-იანი ფასდაკლება',
        detailedProgressReports: 'დეტალური ანგარიშები პროგრესზე',
        mostPopularTier: 'ყველაზე პოპულარული პაკეტი',
        comprehensiveFeedback: 'ამომწურავი უკუკავშირი',
        prioritySupport: 'პრიორიტეტული მხარდაჭერა',
        intensiveSchedule: 'ინტენსიური სასწავლო რეჟიმი',
      },
    },
    dashboard: {
      welcomeStudent: 'გამარჯობა',
      welcomeTeacher: 'გამარჯობა',
      availableTokens: 'ხელმისაწვდომი ტოკენები',
      hoursCompleted: 'გავლილი საათები',
      completedLessons: 'დასრულებული',
      availableLessons: 'ხელმისაწვდომი გაკვეთილები',
      avgRatingLabel: 'საშუალო შეფასება',
      topUp: 'ბალანსის შევსება',
      topUpShort: 'შევსება',
      performanceOverview: 'შედეგების მიმოხილვა',
      completionRate: 'დასრულების მაჩვენებელი',
      activeStudents: 'აქტიური სტუდენტები',
      ratingBasedOn: 'დაფუძნებულია {count} შეფასებაზე',
      ratingUnavailable:
        'გამოჩნდება მას შემდეგ, რაც სტუდენტები შენს გაკვეთილებს შეაფასებენ',
      teacherSummary:
        'მომავალი გაკვეთილები: {upcoming} · დასრულებული: {completed}',
      tokenDetailsOneOnOne: 'ინდივიდუალური',
      tokenDetailsGroup: 'ჯგუფური',
      tokenDetailsFlexible: 'მოქნილი',
      lessonsLabel: 'გაკვეთილი',
      totalStudents: 'სტუდენტების რაოდენობა',
      pendingAnyAvailableTeacher: 'ნებისმიერი თავისუფალი მასწავლებელი',
      waitingForTeacherConfirmation: 'ველოდებით მასწავლებლის დადასტურებას...',
      waitingForAnyTeacher: 'ველოდებით, სანამ რომელიმე მასწავლებელი დაეთანხმება...',
      teacherTip: '💡 რჩევა: მასწავლებლები ჩვეულებრივ 24 საათში პასუხობენ. დადასტურებისთანავე შეტყობინებას მიიღებ!',
      refresh: 'განახლება',
      refreshing: 'მიმდინარეობს განახლება...',
      viewAll: 'ყველას ნახვა',
      todaySchedule: 'დღევანდელი განრიგი',
      recentActivity: 'ბოლო აქტივობა',
      scheduleNewLesson: '+ ახალი გაკვეთილის დაგეგმვა',
      upcomingLessons: 'მომავალი გაკვეთილები',
      pendingRequests: 'მოთხოვნები მოლოდინში',
      openGroupClasses: 'ღია ჯგუფური კლასები',
      available: 'ხელმისაწვდომი',
      coursesComingSoon: 'კურსები მალე დაემატება!',
      assignmentsComingSoon: 'დავალებები მალე დაემატება!',
      noUpcomingLessons: 'მომავალი გაკვეთილები არ გაქვს',
      noRecentActivity: 'ბოლო აქტივობა არ არის',
      noLessonsFound: 'გაკვეთილები ვერ მოიძებნა',
      lessonsFound: 'გაკვეთილი მოიძებნა',
      historyWillAppearHere: 'შენი გაკვეთილების ისტორია აქ გამოჩნდება',
      lessonHistory: 'გაკვეთილების ისტორია',
      feedback: 'უკუკავშირი',
      feedbackTeacherSubtitle:
        'დახურე დასრულებული გაკვეთილები და ერთ ადგილას გადახედე დასწრებას.',
      feedbackStudentSubtitle:
        'წაიკითხე მასწავლებლის კომენტარები და დაადასტურე დასწრება დასრულებულ გაკვეთილებზე.',
      feedbackNeedsAttention: 'საჭიროებს ყურადღებას',
      feedbackReady: 'მზადაა გადასახედად',
      feedbackCompleted: 'დასრულებული',
      feedbackActionNeeded: 'საჭიროა მოქმედება',
      feedbackReview: 'გადახედვა',
      openFeedback: 'გახსნა',
      noFeedbackPending: 'ამჟამად არაფერია მოლოდინში',
      feedbackEmptyHint:
        'გაკვეთილები აქ გამოჩნდება დასრულების შემდეგ, როცა დასწრების დადასტურება ან უკუკავშირი დაგჭირდება.',
      noCompletedFeedback: 'დახურული გაკვეთილი ჯერ არ არის.',
      level: 'დონე',
      joinGroup: 'ჯგუფში შესვლა',
      joining: 'მიმდინარეობს შეერთება...',
      noOpenGroupClasses: 'ამჟამად ღია ჯგუფური კლასი არ არის. შემოიხედე მოგვიანებით.',
    },
    levels: {
      'A1.1': 'A1.1',
      'A1.2': 'A1.2',
      'A2.1': 'A2.1',
      'A2.2': 'A2.2',
      'B1.1': 'B1.1',
      'B1.2': 'B1.2',
      'B2.1': 'B2.1',
      'B2.2': 'B2.2',
      'C1.1': 'C1.1',
      'C1.2': 'C1.2',
      'C2.1': 'C2.1',
      'C2.2': 'C2.2',
    },
    calendar: {
      refresh: 'განახლება',
      refreshing: 'მიმდინარეობს განახლება...',
      scheduleNewLesson: 'ახალი გაკვეთილის დაგეგმვა',
      rescheduleLesson: 'გაკვეთილის გადატანა',
      lessonTopic: 'გაკვეთილის თემა',
      level: 'დონე',
      lessonFocus: 'ფოკუსი (არასავალდებულო)',
      lessonFocusPlaceholder: 'რაზე გსურს ამ გაკვეთილზე ფოკუსირება?',
      selectDate: 'თარიღის არჩევა',
      selectTime: 'დროის არჩევა',
      hour: 'საათი',
      minute: 'წუთი',
      lessonType: 'გაკვეთილის ტიპი',
      groupClass: 'ჯგუფური კლასი',
      oneOnOneLesson: 'ინდივიდუალური გაკვეთილი',
      personalCoaching: 'პირადი კოუჩინგი',
      upToStudents: 'მაქს. 5 სტუდენტი',
      groupClassesInfo: 'ჯგუფური კლასი შედგება, თუ მინიმუმ 2 სტუდენტი შემოუერთდება.',
      scheduleLesson: 'დაგეგმვა',
      reschedule: 'გადატანა',
      cancel: 'გაუქმება',
      classFormat: 'ფორმატი',
      lessonStatus: 'სტატუსი',
      date: 'თარიღი',
      teacher: 'მასწავლებელი',
      student: 'სტუდენტი',
      untitledLesson: 'უსათაურო გაკვეთილი',
      openTeacherAccept: 'ღიაა — დააწკაპუნე მისაღებად',
      openGroupAccept: 'დააწკაპუნე მისაღებად',
      joined: 'შემოუერთდა',
      time: 'დრო',
      duration: 'ხანგრძლივობა',
      view: 'ნახვა',
      notAssigned: 'ჯერ არ არის შერჩეული',
      bookLesson: 'გაკვეთილის დაჯავშნა',
      calendarTitle: 'კალენდარი',
      teacherOpenSummary: 'სტუდენტების ღია მოთხოვნები და შენ მიერ მიღებული გაკვეთილები',
      studentSummary: 'დაგეგმე შენი ინგლისურის გაკვეთილები',
      joinedStudents: 'შემოერთებული სტუდენტები',
      close: 'დახურვა',
      joinLesson: 'გაკვეთილზე შესვლა',
      cancelLesson: 'გაკვეთილის გაუქმება',
      accepting: 'მიმდინარეობს მიღება...',
      acceptGroup: 'ჯგუფის მიღება',
      acceptLesson: 'გაკვეთილის მიღება',
      unknownStudent: 'უცნობი სტუდენტი',
      openAnyTeacher: 'ღიაა — მიღება ნებისმიერ მასწავლებელს შეუძლია',
      scheduledLesson: 'დაგეგმილი გაკვეთილი',
      inProgress: 'მიმდინარეობს',
      finished: 'დასრულებული',
      missedByStudent: 'გამოტოვა სტუდენტმა',
      missedByTeacher: 'გამოტოვა მასწავლებელმა',
      cancelledByStudent: 'გააუქმა სტუდენტმა',
      cancelledByTeacher: 'გააუქმა მასწავლებელმა',
      cancelledBySystem: 'გააუქმა სისტემამ',
      lessonAcceptedTitle: 'გაკვეთილი მიღებულია',
      lessonAcceptedMessage: 'მოთხოვნა მიიღე — გაკვეთილი დაემატა შენს განრიგში.',
      acceptFailedTitle: 'მიღება ვერ მოხერხდა',
      acceptFailedMessage: 'ამ გაკვეთილის მიღება ვერ მოხერხდა.',
      alreadyJoinedTitle: 'უკვე შემოერთებული ხარ',
      joinedGroupTitle: 'შემოუერთდი ჯგუფურ კლასს',
      alreadyJoinedMessage: 'შენ უკვე ხარ ამ ჯგუფურ კლასში.',
      joinedSuccessMessage: 'წარმატებით შემოუერთდი',
      studentsCountSuffix: 'სტუდენტი',
      joinFailedTitle: 'შეერთება ვერ მოხერხდა',
      joinFailedMessage: 'ამ გაკვეთილზე შეერთება ვერ მოხერხდა.',
      classFullMessage: 'ეს კლასი სავსეა, მიუწვდომელია ან შეერთებისთვის დახურულია.',
      joining: 'მიმდინარეობს შეერთება...',
      joinGroupClass: 'ჯგუფურ კლასში შესვლა',
      timePrefix: '—',
      tokenCost: 'ტოკენის ღირებულება',
      availableTokensForThisLessonTypePrefix: 'ამ ტიპის გაკვეთილისთვის ხელმისაწვდომია:',
      availableTokensForThisLessonTypeSuffix: '(მოქნილი ტოკენების ჩათვლით)',
      noTokenAvailablePrefix: 'არ გაქვს ხელმისაწვდომი',
      noTokenAvailableSuffix: '— დაგეგმვამდე შეავსე ბალანსი.',
      tokenLabelOneOnOne: 'ინდივიდუალური ტოკენი',
      tokenLabelGroup: 'ჯგუფური ტოკენი',
      mustBeAtLeast24Hours: 'დრო მინიმუმ 24 საათით მომავალში უნდა იყოს.',
      conflictsWithExistingLesson: 'ეს დრო კვეთს არსებულ გაკვეთილს.',
      newTimeMustBeDifferent: 'ახალი დრო მიმდინარესგან განსხვავებული უნდა იყოს.',
      cannotScheduleLesson: 'გაკვეთილის დაგეგმვა ვერ ხერხდება',
      lessonScheduled: 'გაკვეთილი დაგეგმილია',
      lessonScheduledMessage: 'შენი გაკვეთილი წარმატებით დაიგეგმა.',
      failedToScheduleLesson: 'გაკვეთილის დაგეგმვა ვერ მოხერხდა',
      notEnoughTokensPrefix: 'არ გაქვს საკმარისი',
      notEnoughTokensSuffix: '.',
      schedulingFailed: 'დაგეგმვა ვერ მოხერხდა',
      cannotRescheduleLesson: 'გაკვეთილის გადატანა ვერ ხერხდება',
      lessonRescheduled: 'გაკვეთილი გადატანილია',
      lessonRescheduledMessage: 'შენი გაკვეთილი წარმატებით გადავიდა ახალ დროზე.',
      failedToRescheduleLesson: 'გაკვეთილის გადატანა ვერ მოხერხდა',
      reschedulePermissionDenied: 'სხვისი გაკვეთილის გადატანა არ შეგიძლია',
      reschedulingFailed: 'გადატანა ვერ მოხერხდა',
    },
    notifications: {
      title: 'შეტყობინებები',
      youHave: 'შენ გაქვს',
      notificationSingular: 'შეტყობინება',
      notificationPlural: 'შეტყობინებები',
      all: 'ყველა',
      unread: 'წაუკითხავი',
      read: 'წაკითხული',
      newest: 'უახლესი',
      oldest: 'უძველესი',
      noNotifications: 'შეტყობინებები არ არის',
      caughtUp: 'ყველაფერი წაკითხულია!',
      noRead: 'წაკითხული შეტყობინება ჯერ არ არის',
      checkBack: 'შემოიხედე მოგვიანებით განახლებებისთვის',
      newBadge: 'ახალი',
      from: 'ვისგან',
      messageLabel: 'შეტყობინება',
      close: 'დახურვა',
      markAsRead: 'მონიშნე, როგორც წაკითხული',
    },
    setup: {
      title: 'დაასრულე ანგარიშის მომზადება',
      subtitle: 'მიუთითე სახელი და გვარი. ეს ერთჯერადი მოქმედებაა.',
      firstName: 'სახელი',
      lastName: 'გვარი',
      firstNamePlaceholder: 'შეიყვანე სახელი',
      lastNamePlaceholder: 'შეიყვანე გვარი',
      nameTooShort:
        'სახელი და გვარი მინიმუმ 2 სიმბოლოსგან უნდა შედგებოდეს.',
      updateFailed: 'სახელის განახლება ვერ მოხერხდა.',
      save: 'შენახვა',
      saving: 'მიმდინარეობს შენახვა...',
    },
    cancelLesson: {
      confirmTitle: 'გავაუქმოთ ეს გაკვეთილი?',
      refundWarning:
        'გაკვეთილის გაუქმება შეგიძლია, თუმცა ტოკენი აღარ დაგიბრუნდება, რადგან დაწყებამდე 24 საათზე ნაკლებია დარჩენილი.',
      refundOk: 'გაკვეთილის გაუქმება შეგიძლია და ტოკენი დაგიბრუნდება.',
      keepLesson: 'დატოვება',
      confirmButton: 'გაკვეთილის გაუქმება',
      cancelling: 'მიმდინარეობს გაუქმება...',
      successTitle: 'გაკვეთილი გაუქმდა',
      successMessage: 'გაკვეთილი წარმატებით გაუქმდა.',
      missingIds:
        'გაკვეთილის ან მომხმარებლის იდენტიფიკატორი ვერ მოიძებნა — გაუქმება ვერ ხერხდება',
      failed: 'გაკვეთილის გაუქმება ვერ მოხერხდა',
      errorGeneric: 'გაკვეთილის გაუქმებისას მოხდა შეცდომა',
    },
    topUpModal: {
      balanceSuffix: 'ტოკენი',
      demoNotice:
        'სადემონსტრაციო რეჟიმი — რეალური გადახდა არ ხდება. ტოკენები მყისვე ემატება ტესტირებისთვის.',
      tokenType: 'ტოკენის ტიპი',
      groupTokens: 'ჯგუფური ტოკენები',
      oneOnOneTokens: 'ინდივიდუალური ტოკენები',
      customAmount: 'სასურველი რაოდენობა (1-3 ტოკენი)',
      tokenSingular: 'ტოკენი',
      tokenPlural: 'ტოკენი',
      saveWithBundles: 'დაზოგე პაკეტებით',
      mostPopular: 'ყველაზე პოპულარული',
      perToken: 'ერთ ტოკენზე',
      save: 'დაზოგე',
      paymentMethod: 'გადახდის მეთოდი',
      methodCard: 'საკრედიტო / სადებეტო ბარათი',
      methodApplePay: 'Apple Pay',
      methodPaypal: 'PayPal',
      cardDetails: 'ბარათის მონაცემები',
      cardNumber: 'ბარათის ნომერი',
      expiryDate: 'მოქმედების ვადა',
      cvv: 'CVV',
      selectedBundle: 'არჩეული პაკეტი:',
      discount: 'ფასდაკლება:',
      total: 'ჯამი:',
      cancel: 'გაუქმება',
      processing: 'მიმდინარეობს დამუშავება...',
      pay: 'გადახდა',
      securityNote: '🔒 შენი გადახდის მონაცემები დაცული და დაშიფრულია',
      successTitle: 'გადახდა წარმატებულია',
      successMessage: 'დაემატა {count} {type}.',
      failedTitle: 'გადახდა ვერ განხორციელდა',
      failedGeneric: 'ტოკენების შეძენა ვერ დასრულდა.',
      failedAuth: 'გთხოვ, ხელახლა შედი ანგარიშში და სცადე თავიდან.',
      failedBundle: 'არჩეული პაკეტი არასწორია. სცადე თავიდან.',
    },
    lessonFeedback: {
      yesAttended: 'დიახ',
      noMissed: 'არა',
      attendanceRequired: 'საჭიროა დასწრების დადასტურება',
      confirmTeacherAttendedPrompt:
        'დაადასტურე, დაესწრო თუ არა მასწავლებელი.',
      attendanceRecorded: 'დასწრება დაფიქსირდა',
      thanksForRating: 'მადლობა მასწავლებლის შეფასებისთვის.',
      reportSubmitted: 'შენი შეტყობინება გაიგზავნა.',
      couldNotSubmit: 'გაგზავნა ვერ მოხერხდა',
      tryAgain: 'გთხოვ, სცადე თავიდან.',
      absentNoRating:
        'ამ გაკვეთილზე არდამსწრედ ხარ მონიშნული, ამიტომ მასწავლებლის შეფასება მიუწვდომელია.',
      confirmTeacherAttendance: 'დაადასტურე მასწავლებლის დასწრება',
      teacherReportedMissing:
        'მასწავლებელმა მიუთითა, რომ ეს გაკვეთილი გამოტოვა. დაადასტურე, რა მოხდა.',
      didTeacherAttendQuestion: 'დაესწრო მასწავლებელი ამ გაკვეთილს?',
      youReported: 'შენ მიუთითე:',
      teacherAttended: 'მასწავლებელი დაესწრო',
      teacherMissed: 'მასწავლებელმა გაკვეთილი გამოტოვა',
      didTeacherAttendLabel: 'დაესწრო მასწავლებელი?',
      commentOptional: 'კომენტარი (არასავალდებულო)',
      commentPlaceholderPositive:
        'რა მოგეწონა? რისი გაუმჯობესებაა შესაძლებელი?',
      commentPlaceholderNegative:
        'დაამატე დეტალები იმის შესახებ, რაც მოხდა...',
      submitting: 'მიმდინარეობს გაგზავნა...',
      submitAttendance: 'დასწრების დადასტურება',
      loadingLesson: 'იტვირთება გაკვეთილის დეტალები...',
      waitingForTeacherToClose:
        'ველოდებით, სანამ მასწავლებელი დახურავს ამ გაკვეთილს.',
      teacherMissedLesson:
        'მასწავლებელმა მიუთითა, რომ ეს გაკვეთილი გამოტოვა.',
      markedAbsent: 'ამ გაკვეთილზე არდამსწრედ ხარ მონიშნული.',
      teacherFeedback: 'მასწავლებლის უკუკავშირი',
      newBadge: 'ახალი',
      openMaterials: 'გაზიარებული მასალების გახსნა',
      lessonClosed: 'გაკვეთილი დახურულია',
      youReportedMissing: 'მიუთითე, რომ ეს გაკვეთილი გამოტოვე.',
      attendanceSubmitted:
        'ამ გაკვეთილის დასწრება და უკუკავშირი გაგზავნილია.',
      studentsAttended: 'დაესწრო {attended}/{total} სტუდენტი',
      opensAfterLesson:
        'უკუკავშირი გაკვეთილის დასრულების შემდეგ გაიხსნება.',
      completeLesson: 'გაკვეთილის დასრულება',
      completeLessonHint:
        'დაადასტურე შენი დასწრება, შემდეგ კი აღნიშნე თითოეული სტუდენტის დასწრება და უკუკავშირი.',
      didYouAttend: 'დაესწარი ამ გაკვეთილს?',
      iMissedLesson: 'გამოვტოვე ეს გაკვეთილი',
      confirmYouAttendedPrompt:
        'დაადასტურე, დაესწარი თუ არა ამ გაკვეთილს.',
      markedMissedTitle: 'გაკვეთილი მონიშნულია გამოტოვებულად',
      markedMissedMessage:
        'სტუდენტებს გაეგზავნებათ შეტყობინება დასწრების დასადასტურებლად.',
      feedbackRequiredTitle: 'საჭიროა უკუკავშირი',
      feedbackRequiredMessage:
        'დამსწრე სტუდენტებს უკუკავშირის კომენტარი სჭირდებათ.',
      lessonCompletedTitle: 'გაკვეთილი დასრულებულია',
      lessonCompletedMessage: 'დასწრება და უკუკავშირი შენახულია.',
      studentFallback: 'სტუდენტი',
      didStudentAttend: 'დაესწრო ეს სტუდენტი?',
      rating: 'შეფასება',
      starSingular: 'ვარსკვლავი',
      starPlural: 'ვარსკვლავი',
      feedbackComment: 'უკუკავშირის კომენტარი *',
      feedbackCommentPlaceholder:
        'რა გამოუვიდა კარგად? რაზე უნდა იმუშაოს შემდეგ?',
      materialsLink: 'მასალების ბმული (არასავალდებულო)',
      noteOptional: 'შენიშვნა (არასავალდებულო)',
      notePlaceholder: 'არასავალდებულო შენიშვნა გაცდენის შესახებ...',
      submitAttendanceFeedback: 'დასწრებისა და უკუკავშირის გაგზავნა',
    },
    settings: {
      title: 'პარამეტრები',
      subtitle: 'მართე ანგარიშის პარამეტრები და პირადი მონაცემები',
      emailPushTitle: 'ელფოსტა და Push შეტყობინებები',
      emailPushBody:
        'ყოველთვის ჩართულია, რომ არ გამოგრჩეს სიახლეები გაკვეთილების, დავალებებისა და პლატფორმის შესახებ.',
      theme: 'თემა',
      darkMode: 'მუქი რეჟიმი',
      lightMode: 'ღია რეჟიმი',
      userMode: 'მომხმარებლის რეჟიმი',
      accessText:
        'გაქვს წვდომა როგორც სტუდენტის, ისე მასწავლებლის რეჟიმზე. გადაერთე მათ შორის სხვადასხვა ფუნქციის გამოსაყენებლად.',
      currentModeTeacher: 'მასწავლებლის რეჟიმი',
      currentModeStudent: 'სტუდენტის რეჟიმი',
      notificationPreferences: 'შეტყობინებების პარამეტრები',
      adsEmails: 'სარეკლამო და შეთავაზებების ელფოსტა',
      becomeTeacher: 'გახდი მასწავლებელი',
      becomeTeacherBody:
        'მზად ხარ გამოცდილების გასაზიარებლად? შეავსე განაცხადი და დაიწყე სწავლება ჩვენს პლატფორმაზე მთელი მსოფლიოს სტუდენტებთან.',
      applicationPending: 'შენი განაცხადი განხილვის პროცესშია.',
      applicationApproved: 'შენ უკვე დამტკიცებული მასწავლებელი ხარ.',
      applicationRejected:
        'შენი განაცხადი არ დამტკიცდა. ხელახლა გასაგზავნად დაუკავშირდი მხარდაჭერას.',
      applyButton: 'განაცხადის შევსება',
      profileSettings: 'პროფილის პარამეტრები',
      fullName: 'სახელი და გვარი',
      email: 'ელფოსტა',
      phone: 'ტელეფონი',
      language: 'ენა',
      english: 'ინგლისური',
      georgian: 'ქართული',
    },
  },
} as const;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  isGeorgian: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const getInitialLanguage = (): Language => {
  const savedLanguage = localStorage.getItem('language') as Language | null;
  if (savedLanguage === 'en' || savedLanguage === 'ka') {
    return savedLanguage;
  }

  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const browserLanguage = navigator.language?.toLowerCase() || '';

  if (timeZone === 'Asia/Tbilisi' || timeZone.includes('Tbilisi')) {
    return 'ka';
  }

  if (browserLanguage.startsWith('ka')) {
    return 'ka';
  }

  return 'en';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language === 'ka' ? 'ka' : 'en';
  }, [language]);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  };

  const t = (key: string) => {
    const parts = key.split('.');
    const resolve = (lang: Language) => {
      let current: any = TRANSLATIONS[lang];
      for (const part of parts) {
        current = current?.[part];
      }
      return typeof current === 'string' ? current : undefined;
    };

    return resolve(language) ?? resolve('en') ?? key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, isGeorgian: language === 'ka', t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
};
