import { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ka';

const TRANSLATIONS = {
  en: {
    header: {
      home: 'Home',
      features: 'Features',
      pricing: 'Pricing',
      about: 'About',
      teach: 'Teach',
      dashboard: 'Dashboard',
      login: 'Login',
      signup: 'Sign Up',
      toggleTheme: 'Toggle theme',
      toggleMenu: 'Toggle menu',
    },
    footer: {
      company: 'Company',
      resources: 'Resources',
      legal: 'Legal',
      stayUpdated: 'Stay Updated',
      newsletter: 'Subscribe to our newsletter for learning tips and updates.',
      aboutUs: 'About Us',
      careers: 'Careers',
      press: 'Press',
      blog: 'Blog',
      helpCenter: 'Help Center',
      teachers: 'Teachers',
      community: 'Community',
      contactUs: 'Contact Us',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      cookiePolicy: 'Cookie Policy',
      licensing: 'Licensing',
      copyright: 'All rights reserved.',
      emailPlaceholder: 'Enter your email',
      subscribe: 'Subscribe',
    },
    sidebar: {
      dashboard: 'Dashboard',
      courses: 'Courses',
      history: 'History',
      calendar: 'Calendar',
      assignments: 'Assignments',
      notifications: 'Notifications',
      settings: 'Settings',
      student: 'Student',
      teacher: 'Teacher',
      portal: 'Student Portal',
    },
    auth: {
      backToHome: 'Back to home',
      loading: 'Loading...',
      firstName: 'First Name',
      lastName: 'Last Name',
      firstNamePlaceholder: 'John',
      lastNamePlaceholder: 'Doe',
      loginWelcome: 'Welcome back',
      loginSubtitle: 'Sign in to continue your learning journey',
      registerTitle: 'Create an account',
      registerSubtitle:
        'Start your learning journey today with curated lessons and expert teachers.',
      loginEmailDivider: 'Or continue with email',
      registerEmailDivider: 'Or register with email',
      signIn: 'Sign in',
      signUp: 'Sign up',
      continueWithGoogle: 'Continue with Google',
      facebook: 'Facebook',
      twitter: 'Twitter',
      emailAddress: 'Email Address',
      password: 'Password',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      signInButton: 'Sign in',
      signingIn: 'Signing in...',
      createAccount: 'Create account',
      creatingAccount: 'Creating account...',
      loginFailed: 'Login failed',
      registrationFailed: 'Registration failed',
      accountCreated: 'Account created! You can now login.',
      alreadyHaveAccount: 'Already have an account?',
      doNotHaveAccount: "Don't have an account?",
    },
    landing: {
      heroBadge: 'Now accepting new students',
      heroTitlePre: 'Master English with',
      heroTitleEmphasis: 'Expert Teachers',
      heroSubtitle:
        'Join thousands of students learning English through personalized 1-on-1 lessons and interactive group classes. Start your journey today.',
      heroPrimaryCta: 'Get Started Free',
      heroSecondaryCta: 'View Classes',
      heroStatsStudents: 'Active Students',
      heroStatsTeachers: 'Expert Teachers',
      heroStatsRating: 'Average Rating',
      heroNextLesson: 'Next lesson starts in',
      featuresTitlePre: 'Everything you need to',
      featuresTitleEmphasis: 'master English',
      featuresSubtitle:
        'Our platform combines cutting-edge technology with proven teaching methods to deliver an unmatched learning experience.',
      featuresBadge: 'Features',
      featuresCta: 'Ready to start your learning journey?',
      featuresViewPricing: 'View Pricing Plans',
      featureEasySchedulingTitle: 'Easy Scheduling',
      featureEasySchedulingDescription:
        'Book 1-on-1 lessons or group classes with just a few clicks. Our smart calendar system makes scheduling effortless.',
      featureGroupClassesTitle: 'Group Classes',
      featureGroupClassesDescription:
        'Join small group classes (4 students max) for collaborative learning experiences and peer interaction.',
      featureCefrTitle: 'CEFR-Aligned Courses',
      featureCefrDescription:
        'Structured courses from A1 to C2 levels, perfectly aligned with international language standards.',
      featureProgressTitle: 'Progress Tracking',
      featureProgressDescription:
        'Monitor your improvement with detailed feedback, lesson history, and skill assessments.',
      featureVideoTitle: 'Live Video Lessons',
      featureVideoDescription:
        'High-quality video conferencing built-in. Learn face-to-face with teachers from anywhere.',
      featureFlexibleTitle: 'Flexible Schedule',
      featureFlexibleDescription:
        'Learn at your own pace with 24/7 availability. Choose times that work best for your lifestyle.',
      aboutBadge: 'About Us',
      aboutTitlePre: 'Your trusted partner in',
      aboutTitleEmphasis: 'language learning',
      aboutParagraph1:
        'British World has been revolutionizing online language education since 2014. We\'ve helped thousands of students achieve their English language goals through personalized instruction and innovative technology.',
      aboutParagraph2:
        'Our platform combines the expertise of certified teachers with cutting-edge learning tools to create an engaging, effective, and flexible learning experience. Whether you\'re preparing for exams, advancing your career, or simply love learning, we\'re here to support your journey.',
      aboutParagraph3:
        'With a community of over 10,000 active students and 500+ qualified teachers, British World is more than just a learning platform-it\'s a global community dedicated to language excellence.',
      aboutYearsExperience: 'Years Experience',
      valueExcellenceTitle: 'Excellence',
      valueExcellenceDescription:
        'We maintain the highest standards in teaching and student support.',
      valueCommunityTitle: 'Global Community',
      valueCommunityDescription:
        'Connect with students and teachers from around the world.',
      valueStudentCenteredTitle: 'Student-Centered',
      valueStudentCenteredDescription:
        'Your learning goals and success are at the heart of everything we do.',
      valueTrustTitle: 'Trust & Safety',
      valueTrustDescription:
        'Verified teachers, secure payments, and a safe learning environment.',
      pricingBadge: 'Pricing',
      pricingTitlePre: 'Simple, transparent',
      pricingTitleEmphasis: 'pricing',
      pricingSubtitle:
        'Choose the plan that fits your learning goals. All plans include access to certified teachers and our full platform features.',
      pricingFooterNote: 'Prices shown in EUR for group classes.',
      pricingFooterCustom: 'Need a custom plan?',
      contactUs: 'Contact us',
      viewPricingPlans: 'View Pricing Plans',
      featuresCta: 'Ready to start your learning journey?',
    },
    pricing: {
      tokensLabel: 'Tokens',
      perLesson: 'per lesson',
      save: 'Save',
      mostPopular: 'Most Popular',
      getStarted: 'Get Started',
      needCustomPlan: 'Need a custom plan?',
      contactUs: 'Contact us',
      alignedNote: 'Lingoda-aligned prices shown in EUR for group classes.',
      features: {
        fourLessons: '4 live group lessons',
        eightLessons: '8 live group lessons',
        sixteenLessons: '16 live group lessons',
        thirtyTwoLessons: '32 live group lessons',
        flexibleScheduling: 'Flexible scheduling',
        progressTracking: 'Progress tracking',
        balancedWeeklyPace: 'Balanced weekly pace',
        lessonReminders: 'Lesson reminders',
        discountedTier: '20% discounted tier',
        detailedProgressReports: 'Detailed progress reports',
        mostPopularTier: 'Most popular Lingoda tier',
        comprehensiveFeedback: 'Comprehensive feedback',
        prioritySupport: 'Priority support',
        intensiveSchedule: 'Intensive learning schedule',
      },
    },
    dashboard: {
      welcomeStudent: 'Welcome back',
      welcomeTeacher: 'Welcome back',
      availableTokens: 'Available Tokens',
      hoursCompleted: 'Hours Completed',
      completedLessons: 'Completed',
      availableLessons: 'Available Lessons',
      avgRatingLabel: 'Avg Rating',
      topUp: 'Top up',
      tokenDetailsOneOnOne: '1-on-1',
      tokenDetailsGroup: 'Group',
      tokenDetailsFlexible: 'Flexible',
      favoriteTeachersTitle: 'Your Favorite Teachers',
      lessonsLabel: 'lessons',
      totalStudents: 'Total Students',
      pendingAnyAvailableTeacher: 'Any Available Teacher',
      waitingForTeacherConfirmation: 'Waiting for teacher confirmation...',
      waitingForAnyTeacher: "Waiting for any teacher to accept...",
      teacherTip: "💡 Tip: Teachers usually respond within 24 hours. You'll receive a notification once they accept!",
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      viewAll: 'View All',
      todaySchedule: "Today's Schedule",
      recentActivity: 'Recent Activity',
      scheduleNewLesson: '+ Schedule New Lesson',
      upcomingLessons: 'Upcoming Lessons',
      pendingRequests: 'Pending Requests',
      openGroupClasses: 'Open Group Classes',
      available: 'available',
      coursesComingSoon: 'Courses Coming Soon!',
      assignmentsComingSoon: 'Assignments Coming Soon!',
      noUpcomingLessons: 'No upcoming lessons',
      noRecentActivity: 'No recent activity',
      noLessonsFound: 'No lessons found',
      lessonsFound: 'lesson(s) found',
      historyWillAppearHere: 'Your lesson history will appear here',
      lessonHistory: 'Lesson History',
      level: 'Level',
      joinGroup: 'Join Group',
      joining: 'Joining...',
      noOpenGroupClasses: 'No open group classes right now. Check back soon.',
      settingsTitle: 'Settings',
      settingsSubtitle: 'Manage your account preferences and settings',
      language: 'Language',
      english: 'English',
      georgian: 'Georgian',
    },
    levels: {
      'A1.1': 'A1.1',
      'A1.2': 'A1.2',
      'A2.1': 'A2.1',
      'A2.2': 'A2.2',
      'B1.1': 'B1.1',
      'B1.2': 'B1.2',
      'B2.1': 'B2.1',
      'B2.2': 'B2.2',
      'C1.1': 'C1.1',
      'C1.2': 'C1.2',
      'C2.1': 'C2.1',
      'C2.2': 'C2.2',
    },
    calendar: {
      refresh: 'Refresh',
      refreshing: 'Refreshing...',
      scheduleNewLesson: 'Schedule New Lesson',
      rescheduleLesson: 'Reschedule Lesson',
      lessonTopic: 'Lesson Topic',
      level: 'Level',
      lessonFocus: 'Lesson Focus (Optional)',
      lessonFocusPlaceholder: 'What would you like to focus on in this lesson?',
      selectDate: 'Select Date',
      selectTime: 'Select Time',
      hour: 'Hour',
      minute: 'Minute',
      lessonType: 'Lesson Type',
      groupClass: 'Group Class',
      oneOnOneLesson: '1-on-1 Lesson',
      personalCoaching: 'Personal coaching',
      upToStudents: 'Up to 5 students',
      groupClassesInfo: 'Group classes proceed when at least 2 students are joined.',
      scheduleLesson: 'Schedule Lesson',
      reschedule: 'Reschedule Lesson',
      cancel: 'Cancel',
      classFormat: 'Class Format',
      lessonStatus: 'Lesson Status',
      date: 'Date',
      teacher: 'Teacher',
      student: 'Student',
      untitledLesson: 'Untitled Lesson',
      openTeacherAccept: 'Open - tap to accept',
      openGroupAccept: 'tap to accept',
      joined: 'joined',
      time: 'Time',
      duration: 'Duration',
      view: 'View',
      notAssigned: 'Not Assigned',
      bookLesson: 'Book Lesson',
      calendarTitle: 'Calendar',
      teacherOpenSummary: 'Open requests from students and lessons you have accepted',
      studentSummary: 'Schedule your English lessons',
      joinedStudents: 'Joined Students',
      close: 'Close',
      joinLesson: 'Join lesson',
      cancelLesson: 'Cancel lesson',
      accepting: 'Accepting...',
      acceptGroup: 'Accept group',
      acceptLesson: 'Accept lesson',
      unknownStudent: 'Unknown student',
      openAnyTeacher: 'Open — any teacher can accept',
      notAssigned: 'Not assigned',
      scheduledLesson: 'Scheduled Lesson',
      inProgress: 'In Progress',
      finished: 'Finished',
      missedByStudent: 'Missed by Student',
      missedByTeacher: 'Missed by Teacher',
      cancelledByStudent: 'Cancelled by Student',
      cancelledByTeacher: 'Cancelled by Teacher',
      cancelledBySystem: 'Cancelled by System',
      lessonAcceptedTitle: 'Lesson accepted',
      lessonAcceptedMessage: 'You have accepted this lesson request.',
      acceptFailedTitle: 'Accept failed',
      acceptFailedMessage: 'Could not accept this lesson.',
      alreadyJoinedTitle: 'Already Joined',
      joinedGroupTitle: 'Joined Group Class',
      alreadyJoinedMessage: 'You are already in this group class.',
      joinedSuccessMessage: 'Joined successfully',
      joinFailedTitle: 'Join Failed',
      joinFailedMessage: 'Could not join this lesson.',
      classFullMessage: 'This class is full, unavailable, or no longer open for joining.',
      joining: 'Joining...',
      joinGroupClass: 'Join Group Class',
      reschedule: 'Reschedule',
      timePrefix: 'at',
      tokenCost: 'Token Cost',
      availableTokensForThisLessonTypePrefix: 'Available for this lesson type:',
      availableTokensForThisLessonTypeSuffix: '(including flexible tokens)',
      noTokenAvailablePrefix: 'No',
      noTokenAvailableSuffix: 'available. Please top up to schedule.',
      mustBeAtLeast24Hours: 'Must be at least 24 hours in the future.',
      conflictsWithExistingLesson: 'Conflicts with an existing lesson.',
      newTimeMustBeDifferent: 'New time must be different from current time.',
      cannotScheduleLesson: 'Cannot schedule lesson',
      lessonScheduled: 'Lesson Scheduled',
      lessonScheduledMessage: 'Your lesson has been successfully scheduled.',
      failedToScheduleLesson: 'Failed to schedule lesson',
      notEnoughTokensPrefix: 'You do not have enough',
      notEnoughTokensSuffix: '',
      schedulingFailed: 'Scheduling Failed',
      cannotRescheduleLesson: 'Cannot reschedule lesson',
      lessonRescheduled: 'Lesson Rescheduled',
      lessonRescheduledMessage: 'Your lesson has been successfully rescheduled.',
      failedToRescheduleLesson: 'Failed to reschedule lesson',
      reschedulePermissionDenied: 'You are not allowed to reschedule other people\'s lessons',
      reschedulingFailed: 'Rescheduling Failed',
    },
    notifications: {
      title: 'Notifications',
      youHave: 'You have',
      notificationSingular: 'notification',
      notificationPlural: 'notifications',
      all: 'All',
      unread: 'Unread',
      read: 'Read',
      newest: 'Newest',
      oldest: 'Oldest',
      noNotifications: 'No notifications',
      caughtUp: "You're all caught up!",
      noRead: 'No read notifications yet',
      checkBack: 'Check back later for updates',
      newBadge: 'New',
      from: 'From',
      messageLabel: 'Message',
      close: 'Close',
      markAsRead: 'Mark as Read',
    },
  },
  ka: {
    header: {
      home: 'მთავარი',
      features: 'ფუნქციები',
      pricing: 'ფასები',
      about: 'ჩვენ შესახებ',
      teach: 'ასწავლე',
      dashboard: 'დეშბორდი',
      login: 'შესვლა',
      signup: 'რეგისტრაცია',
      toggleTheme: 'თემის გადართვა',
      toggleMenu: 'მენიუს გადართვა',
    },
    footer: {
      company: 'კომპანია',
      resources: 'რესურსები',
      legal: 'იურიდიული',
      stayUpdated: 'იყავი განახლებულ მდგომარეობაში',
      newsletter: 'გამოიწერე ჩვენი სიახლეები სასარგებლო რჩევებისა და განახლებებისთვის.',
      aboutUs: 'ჩვენ შესახებ',
      careers: 'ვაკანსიები',
      press: 'პრესა',
      blog: 'ბლოგი',
      helpCenter: 'დახმარების ცენტრი',
      teachers: 'მასწავლებლები',
      community: 'საზოგადოება',
      contactUs: 'დაგვიკავშირდი',
      privacyPolicy: 'კონფიდენციალურობის პოლიტიკა',
      termsOfService: 'მომსახურების პირობები',
      cookiePolicy: 'ქუქი-ფაილების პოლიტიკა',
      licensing: 'ლიცენზირება',
      copyright: 'ყველა უფლება დაცულია.',
      emailPlaceholder: 'შეიყვანე ელფოსტა',
      subscribe: 'გამოწერა',
    },
    sidebar: {
      dashboard: 'დეშბორდი',
      courses: 'კურსები',
      history: 'ისტორია',
      calendar: 'კალენდარი',
      assignments: 'დავალებები',
      notifications: 'შეტყობინებები',
      settings: 'პარამეტრები',
      student: 'სტუდენტი',
      teacher: 'მასწავლებელი',
      portal: 'სტუდენტის პორტალი',
    },
    auth: {
      backToHome: 'მთავარზე დაბრუნება',
      loading: 'იტვირთება...',
      firstName: 'სახელი',
      lastName: 'გვარი',
      firstNamePlaceholder: 'გიორგი',
      lastNamePlaceholder: 'ბერიძე',
      loginWelcome: 'კეთილი დაბრუნება',
      loginSubtitle: 'შედით თქვენს ანგარიშში სწავლის გასაგრძელებლად',
      registerTitle: 'ანგარიშის შექმნა',
      registerSubtitle:
        'დაიწყე სწავლის გზა დღესვე, მომზადებული გაკვეთილებით და პროფესიონალი მასწავლებლებით.',
      loginEmailDivider: 'ან გააგრძელე ელფოსტით',
      registerEmailDivider: 'ან დარეგისტრირდი ელფოსტით',
      signIn: 'შესვლა',
      signUp: 'რეგისტრაცია',
      continueWithGoogle: 'გაგრძელება Google-ით',
      facebook: 'Facebook',
      twitter: 'Twitter',
      emailAddress: 'ელფოსტის მისამართი',
      password: 'პაროლი',
      rememberMe: 'დამახსოვრება',
      forgotPassword: 'დაგავიწყდა პაროლი?',
      signInButton: 'შესვლა',
      signingIn: 'შესვლა...',
      createAccount: 'ანგარიშის შექმნა',
      creatingAccount: 'იქმნება ანგარიში...',
      loginFailed: 'შესვლა ვერ მოხერხდა',
      registrationFailed: 'რეგისტრაცია ვერ მოხერხდა',
      accountCreated: 'ანგარიში შეიქმნა! ახლა შეგიძლია შეხვიდე.',
      alreadyHaveAccount: 'უკვე გაქვს ანგარიში?',
      doNotHaveAccount: 'არ გაქვს ანგარიში?',
    },
    landing: {
      heroBadge: 'ახალი სტუდენტების მიღება მიმდინარეობს',
      heroTitlePre: 'ინგლისურის დაუფლება',
      heroTitleEmphasis: 'პროფესიონალ მასწავლებლებთან',
      heroSubtitle:
        'ათასობით სტუდენტი უკვე სწავლობს ინგლისურს პერსონალიზებული 1-დან 1 გაკვეთილებით და ინტერაქტიული ჯგუფური კლასებით. დაიწყე შენი გზა დღესვე.',
      heroPrimaryCta: 'დაწყება უფასოდ',
      heroSecondaryCta: 'კლასების ნახვა',
      heroStatsStudents: 'აქტიური სტუდენტი',
      heroStatsTeachers: 'პროფესიონალი მასწავლებელი',
      heroStatsRating: 'საშუალო შეფასება',
      heroNextLesson: 'შემდეგი გაკვეთილი იწყება',
      featuresTitlePre: 'ყველაფერი რაც გჭირდება',
      featuresTitleEmphasis: 'ინგლისურის დასაუფლებლად',
      featuresSubtitle:
        'ჩვენი პლატფორმა აერთიანებს თანამედროვე ტექნოლოგიასა და დადასტურებულ სწავლების მეთოდებს.',
      featuresBadge: 'ფუნქციები',
      featuresCta: 'მზად ხარ სწავლა დაიწყო?',
      featuresViewPricing: 'ფასების ნახვა',
      featureEasySchedulingTitle: 'მარტივი დაგეგმვა',
      featureEasySchedulingDescription:
        'დაჯავშნე 1-დან 1 გაკვეთილები ან ჯგუფური კლასები რამდენიმე დაწკაპებით. ჩვენი ჭკვიანი კალენდარი დაგეგმვას ამარტივებს.',
      featureGroupClassesTitle: 'ჯგუფური კლასები',
      featureGroupClassesDescription:
        'შეუერთდი მცირე ჯგუფურ კლასებს (მაქს. 4 სტუდენტი) თანამშრომლობითი სწავლისთვის და ურთიერთქმედებისთვის.',
      featureCefrTitle: 'CEFR სტანდარტზე მორგებული კურსები',
      featureCefrDescription:
        'კურსები A1-დან C2-მდე დონეებით, სრულ შესაბამისობაში საერთაშორისო ენის სტანდარტებთან.',
      featureProgressTitle: 'პროგრესის თვალყურის დევნება',
      featureProgressDescription:
        'დააკვირდი შენს წინსვლას დეტალური უკუკავშირით, გაკვეთილების ისტორიით და უნარების შეფასებით.',
      featureVideoTitle: 'ცოცხალი ვიდეო გაკვეთილები',
      featureVideoDescription:
        'მაღალი ხარისხის ვიდეოკონფერენცია ჩაშენებულია. ისწავლე მასწავლებლებთან პირისპირ ნებისმიერი ადგილიდან.',
      featureFlexibleTitle: 'მოქნილი განრიგი',
      featureFlexibleDescription:
        'ისწავლე შენს ტემპში 24/7 ხელმისაწვდომობით. აირჩიე დრო, რომელიც საუკეთესოდ გერგება.',
      aboutBadge: 'ჩვენ შესახებ',
      aboutTitlePre: 'სანდო პარტნიორი',
      aboutTitleEmphasis: 'ენის სწავლებაში',
      aboutParagraph1:
        'British World 2014 წლიდან ცვლის ონლაინ ენის სწავლებას. ჩვენ დავეხმარეთ ათასობით სტუდენტს ინგლისურის მიზნების მიღწევაში პერსონალური სწავლებით და თანამედროვე ტექნოლოგიებით.',
      aboutParagraph2:
        'ჩვენი პლატფორმა აერთიანებს სერტიფიცირებული მასწავლებლების გამოცდილებას და თანამედროვე სასწავლო ინსტრუმენტებს. იქნება ეს გამოცდისთვის მზადება, კარიერის განვითარება თუ უბრალოდ სწავლა - აქ შენი გზა მხარდაჭერილია.',
      aboutParagraph3:
        '10,000-ზე მეტი აქტიური სტუდენტით და 500+ კვალიფიციური მასწავლებლით, British World არის გლობალური საზოგადოება, რომელიც ენის სრულყოფილებას ემსახურება.',
      aboutYearsExperience: 'წლის გამოცდილება',
      valueExcellenceTitle: 'სრულყოფილება',
      valueExcellenceDescription:
        'ჩვენ ვინარჩუნებთ სწავლებისა და სტუდენტური მხარდაჭერის უმაღლეს სტანდარტებს.',
      valueCommunityTitle: 'გლობალური საზოგადოება',
      valueCommunityDescription:
        'დაუკავშირდი სტუდენტებსა და მასწავლებლებს მთელი მსოფლიოდან.',
      valueStudentCenteredTitle: 'სტუდენტზე მორგებული',
      valueStudentCenteredDescription:
        'შენი მიზნები და წარმატება ჩვენს საქმიანობაში უმთავრესია.',
      valueTrustTitle: 'ნდობა და უსაფრთხოება',
      valueTrustDescription:
        'დამოწმებული მასწავლებლები, უსაფრთხო გადახდები და უსაფრთხო სასწავლო გარემო.',
      pricingBadge: 'ფასები',
      pricingTitlePre: 'მარტივი და გამჭვირვალე',
      pricingTitleEmphasis: 'ფასები',
      pricingSubtitle:
        'აირჩიე გეგმა, რომელიც შეესაბამება შენს მიზნებს. ყველა გეგმა მოიცავს სერტიფიცირებულ მასწავლებლებს და პლატფორმის სრულ ფუნქციონალს.',
      pricingFooterNote: 'ფასები ნაჩვენებია ევროში ჯგუფური კლასებისთვის.',
      pricingFooterCustom: 'გჭირდება ინდივიდუალური გეგმა?',
      contactUs: 'დაგვიკავშირდი',
      viewPricingPlans: 'ფასების ნახვა',
      featuresCta: 'მზად ხარ სწავლა დაიწყო?',
    },
    pricing: {
      tokensLabel: 'ქულა',
      perLesson: 'ერთ გაკვეთილზე',
      save: 'დაზოგე',
      mostPopular: 'ყველაზე პოპულარული',
      getStarted: 'დაწყება',
      needCustomPlan: 'გჭირდება ინდივიდუალური გეგმა?',
      contactUs: 'დაგვიკავშირდი',
      alignedNote: 'Lingoda-სთან შესაბამისი ფასები ნაჩვენებია ევროში ჯგუფური კლასებისთვის.',
      features: {
        fourLessons: '4 ცოცხალი ჯგუფური გაკვეთილი',
        eightLessons: '8 ცოცხალი ჯგუფური გაკვეთილი',
        sixteenLessons: '16 ცოცხალი ჯგუფური გაკვეთილი',
        thirtyTwoLessons: '32 ცოცხალი ჯგუფური გაკვეთილი',
        flexibleScheduling: 'მოქნილი დაგეგმვა',
        progressTracking: 'პროგრესის თვალყურის დევნება',
        balancedWeeklyPace: 'დაბალანსებული კვირეული ტემპი',
        lessonReminders: 'გაკვეთილის შეხსენებები',
        discountedTier: '20%-იანი ფასდაკლებული დონე',
        detailedProgressReports: 'დეტალური პროგრესის ანგარიშები',
        mostPopularTier: 'Lingoda-ს ყველაზე პოპულარული დონე',
        comprehensiveFeedback: 'სრული უკუკავშირი',
        prioritySupport: 'პრიორიტეტული მხარდაჭერა',
        intensiveSchedule: 'ინტენსიური სასწავლო გეგმა',
      },
    },
    dashboard: {
      welcomeStudent: 'კეთილი დაბრუნება',
      welcomeTeacher: 'კეთილი დაბრუნება',
      availableTokens: 'ხელმისაწვდომი ტოკენები',
      hoursCompleted: 'დასრულებული საათები',
      completedLessons: 'დასრულებული',
      availableLessons: 'ხელმისაწვდომი გაკვეთილები',
      avgRatingLabel: 'საშუალო შეფასება',
      topUp: 'დატოპვა',
      tokenDetailsOneOnOne: '1-ზე-1',
      tokenDetailsGroup: 'ჯგუფი',
      tokenDetailsFlexible: 'ფლექსიბლ',
      favoriteTeachersTitle: 'შენს საყვარელ მასწავლებლები',
      lessonsLabel: 'გაკვეთილი',
      totalStudents: 'სტუდენტთა რაოდენობა',
      pendingAnyAvailableTeacher: 'ხელმისაწვდომი მასწავლებელი',
      waitingForTeacherConfirmation: 'მომზადებაშია - ველოდებით მასწავლებლის დადასტურებას...',
      waitingForAnyTeacher: 'ველოდებით, სანამ რომელიმე მასწავლებელი მიიღებს...',
      teacherTip: '💡 რჩევა: მასწავლებლები ჩვეულებრივ პასუხობენ 24 საათში. მიღების შემდეგ მიიღებთ შეტყობინებას!',
      refresh: 'განახლება',
      refreshing: 'მიმდინარეობს განახლება...',
      viewAll: 'ყველას ნახვა',
      todaySchedule: 'დღევანდელი გრაფიკი',
      recentActivity: 'ბოლო აქტივობა',
      scheduleNewLesson: '+ ახალი გაკვეთილის დაგეგმვა',
      upcomingLessons: 'მომავალი გაკვეთილები',
      pendingRequests: 'მოსაცდელი მოთხოვნები',
      openGroupClasses: 'ღია ჯგუფური კლასები',
      available: 'ხელმისაწვდომია',
      coursesComingSoon: 'კურსები მომდევნო ეტაპზეა!',
      assignmentsComingSoon: 'დავალებები მომდევნო ეტაპზეა!',
      noUpcomingLessons: 'მომავალი გაკვეთილები არ არის',
      noRecentActivity: 'ბოლო აქტივობა არ არის',
      noLessonsFound: 'გაკვეთილები ვერ მოიძებნა',
      lessonsFound: 'გაკვეთილი მოიძებნა',
      historyWillAppearHere: 'შენი გაკვეთილების ისტორია აქ გამოჩნდება',
      lessonHistory: 'გაკვეთილების ისტორია',
      level: 'დონე',
      joinGroup: 'ჯგუფში შესვლა',
      joining: 'ერთდება...',
      noOpenGroupClasses: 'ამჟამად ღია ჯგუფური კლასები არ არის. დაბრუნდი მოგვიანებით.',
      settingsTitle: 'პარამეტრები',
      settingsSubtitle: 'მართე შენი ანგარიშის პარამეტრები და მორგებები',
      language: 'ენა',
      english: 'ინგლისური',
      georgian: 'ქართული',
    },
    levels: {
      'A1.1': 'A1.1',
      'A1.2': 'A1.2',
      'A2.1': 'A2.1',
      'A2.2': 'A2.2',
      'B1.1': 'B1.1',
      'B1.2': 'B1.2',
      'B2.1': 'B2.1',
      'B2.2': 'B2.2',
      'C1.1': 'C1.1',
      'C1.2': 'C1.2',
      'C2.1': 'C2.1',
      'C2.2': 'C2.2',
    },
    calendar: {
      refresh: 'განახლება',
      refreshing: 'მიმდინარეობს განახლება...',
      scheduleNewLesson: 'ახალი გაკვეთილის დაგეგმვა',
      rescheduleLesson: 'გაკვეთილის გადატანა',
      lessonTopic: 'გაკვეთილის თემა',
      level: 'დონე',
      lessonFocus: 'ფოკუსი (არასავალდებულო)',
      lessonFocusPlaceholder: 'რა თემაზე გსურს ამ გაკვეთილზე ფოკუსირება?',
      selectDate: 'თარიღის არჩევა',
      selectTime: 'დროის არჩევა',
      hour: 'საათი',
      minute: 'წუთი',
      lessonType: 'გაკვეთილის ტიპი',
      groupClass: 'ჯგუფური კლასი',
      oneOnOneLesson: 'ინდივიდუალური გაკვეთილი',
      personalCoaching: 'პირადი კოუჩინგი',
      upToStudents: 'მაქს. 5 სტუდენტი',
      groupClassesInfo: 'ჯგუფური კლასები მიმდინარეობს, როცა მინიმუმ 2 სტუდენტი შეუერთდება.',
      scheduleLesson: 'დაგეგმვა',
      reschedule: 'გადატანა',
      cancel: 'გაუქმება',
      classFormat: 'ფორმატი',
      lessonStatus: 'სტატუსი',
      date: 'თარიღი',
      teacher: 'მასწავლებელი',
      student: 'სტუდენტი',
      untitledLesson: 'უსათაურო გაკვეთილი',
      openTeacherAccept: 'ღიაა - დააწკაპე მისაღებად',
      openGroupAccept: 'დააწკაპე მისაღებად',
      joined: 'შემოუერთდა',
      time: 'დრო',
      duration: 'ხანგრძლივობა',
      view: 'ნახვა',
      notAssigned: 'არ არის მინიჭებული',
      bookLesson: 'გაკვეთილის დაჯავშნა',
      calendarTitle: 'კალენდარი',
      teacherOpenSummary: 'სტუდენტების ღია მოთხოვნები და უკვე მიღებული გაკვეთილები',
      studentSummary: 'დაგეგმე შენი ინგლისურის გაკვეთილები',
      joinedStudents: 'შეერთებული სტუდენტები',
      close: 'დახურვა',
      joinLesson: 'გაკვეთილზე შესვლა',
      cancelLesson: 'გაკვეთილის გაუქმება',
      accepting: 'მიღება...',
      acceptGroup: 'ჯგუფის მიღება',
      acceptLesson: 'გაკვეთილის მიღება',
      unknownStudent: 'უცნობი სტუდენტი',
      openAnyTeacher: 'ღიაა — ნებისმიერმა მასწავლებელმა შეიძლება მიიღოს',
      notAssigned: 'არ არის მინიჭებული',
      scheduledLesson: 'დაგეგმილი გაკვეთილი',
      inProgress: 'მიმდინარეობს',
      finished: 'დასრულებული',
      missedByStudent: 'გამოტოვა სტუდენტმა',
      missedByTeacher: 'გამოტოვა მასწავლებელმა',
      cancelledByStudent: 'გაუქმდა სტუდენტის მიერ',
      cancelledByTeacher: 'გაუქმდა მასწავლებლის მიერ',
      cancelledBySystem: 'გაუქმდა სისტემის მიერ',
      lessonAcceptedTitle: 'გაკვეთილი მიღებულია',
      lessonAcceptedMessage: 'შენ მიიღე ეს გაკვეთილის მოთხოვნა.',
      acceptFailedTitle: 'მიღება ვერ მოხერხდა',
      acceptFailedMessage: 'ამ გაკვეთილის მიღება ვერ მოხერხდა.',
      alreadyJoinedTitle: 'უკვე შეერთებული ხარ',
      joinedGroupTitle: 'ჯგუფურ კლასს შეუერთდი',
      alreadyJoinedMessage: 'შენ უკვე ხარ ამ ჯგუფურ კლასში.',
      joinedSuccessMessage: 'შეერთება წარმატებულია',
      joinFailedTitle: 'შეერთება ვერ მოხერხდა',
      joinFailedMessage: 'ამ გაკვეთილზე შეერთება ვერ მოხერხდა.',
      classFullMessage: 'ეს კლასი სავსეა, მიუწვდომელია ან აღარაა შეერთებისთვის ღია.',
      joining: 'ერთდება...',
      joinGroupClass: 'ჯგუფურ კლასში შესვლა',
      reschedule: 'გადატანა',
      timePrefix: 'საათზე',
      tokenCost: 'ტოკენის ღირებულება',
      availableTokensForThisLessonTypePrefix: 'ამ ტიპის გაკვეთილისთვის ხელმისაწვდომია:',
      availableTokensForThisLessonTypeSuffix: '(მოიცავს ფლექსიბლ ტოკენებს)',
      noTokenAvailablePrefix: 'არ არის',
      noTokenAvailableSuffix: 'ხელმისაწვდომი. დაგეგმვამდე საჭიროა შევსება.',
      mustBeAtLeast24Hours: 'უნდა იყოს მინიმუმ 24 საათით მომავალში.',
      conflictsWithExistingLesson: 'კონფლიქტშია არსებულ გაკვეთილთან.',
      newTimeMustBeDifferent: 'ახალი დრო უნდა განსხვავდებოდეს მიმდინარე დროისგან.',
      cannotScheduleLesson: 'გაკვეთილის დაგეგმვა ვერ ხერხდება',
      lessonScheduled: 'გაკვეთილი დაგეგმილია',
      lessonScheduledMessage: 'შენი გაკვეთილი წარმატებით დაიგეგმა.',
      failedToScheduleLesson: 'გაკვეთილის დაგეგმვა ვერ მოხერხდა',
      notEnoughTokensPrefix: 'არ გაქვს საკმარისი',
      notEnoughTokensSuffix: '',
      schedulingFailed: 'დაგეგმვა ვერ მოხერხდა',
      cannotRescheduleLesson: 'გაკვეთილის გადატანა ვერ ხერხდება',
      lessonRescheduled: 'გაკვეთილი გადატანილია',
      lessonRescheduledMessage: 'შენი გაკვეთილი წარმატებით გადაიტანეს.',
      failedToRescheduleLesson: 'გაკვეთილის გადატანა ვერ მოხერხდა',
      reschedulePermissionDenied: 'სხვისი გაკვეთილის გადატანის უფლება არ გაქვს',
      reschedulingFailed: 'გადატანა ვერ მოხერხდა',
    },
    notifications: {
      title: 'შეტყობინებები',
      youHave: 'შენ გაქვს',
      notificationSingular: 'შეტყობინება',
      notificationPlural: 'შეტყობინებები',
      all: 'ყველა',
      unread: 'წაუკითხავი',
      read: 'წაკითხული',
      newest: 'ახლა',
      oldest: 'ყველაზე ძველი',
      noNotifications: 'შეტყობინებები არ არის',
      caughtUp: 'შენ ყველაფერს მოუსმენ!',
      noRead: 'წაკითხული შეტყობინებები არ არის',
      checkBack: 'ჩამოწმე შემდეგში განახლებებისთვის',
      newBadge: 'ახალი',
      from: 'ვინც',
      messageLabel: 'შეტყობინება',
      close: 'დახურვა',
      markAsRead: 'მონიშნე როგორც წაკითხული',
    },
  },
} as const;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  isGeorgian: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

const getInitialLanguage = (): Language => {
  const savedLanguage = localStorage.getItem('language') as Language | null;
  if (savedLanguage === 'en' || savedLanguage === 'ka') {
    return savedLanguage;
  }

  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const browserLanguage = navigator.language?.toLowerCase() || '';

  if (timeZone === 'Asia/Tbilisi' || timeZone.includes('Tbilisi')) {
    return 'ka';
  }

  if (browserLanguage.startsWith('ka')) {
    return 'ka';
  }

  return 'en';
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language === 'ka' ? 'ka' : 'en';
  }, [language]);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  };

  const t = (key: string) => {
    const parts = key.split('.');
    const resolve = (lang: Language) => {
      let current: any = TRANSLATIONS[lang];
      for (const part of parts) {
        current = current?.[part];
      }
      return typeof current === 'string' ? current : undefined;
    };

    return resolve(language) ?? resolve('en') ?? key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage, isGeorgian: language === 'ka', t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
};
